test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

cloudflare:
  service: S3
  endpoint: https://<%= ENV["R2_ACCOUNT_ID"] %>.r2.cloudflarestorage.com
  access_key_id: <%= ENV["R2_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["R2_SECRET_ACCESS_KEY"] %>
  bucket: <%= ENV["R2_BUCKET"] %>
  region: auto
  request_checksum_calculation: "when_required"
  response_checksum_validation: "when_required"
